site_name: Guidelines and Documentation
pages:
- Home: 'index.md'
- Teacher Guidelines:
  - 'Getting Started: Designing your Course': '01_getting-started.md'
  - 'Curriculum Design': '02_curriculum-design.md'
  - 'Recommended Course Cycle': '03_course-cycle-schedule.md'
  - 'Setting up the course's properties': '04_course-settings.md'
  - 'Granting permissions to users': '04a_course-permissions.md'
  - 'Adding your content to the platform': '05_adding-content.md'
  - 'Quiz Design': '06-quiz-design.md'
  - 'Adding quizzes and questions': '07_adding-quizzes-and-questions.md'
  - 'Quiz Submissions': '08_quiz-submissions.md'
  - 'Masquerade': '09_masquerade.md'
  - 'Peer Assessment': '10_peer-assessment.md'
  - 'LTI': '11_lti.md'
  - 'CodeOcean': '12_code-ocean.md'
  - 'Static Pages': '15_static_pages.md'
  - 'Community Management': '19_community-management.md'
  - 'End of Course': '20_end-of-course.md'
  - 'Communication Matrix': '21_communication-matrix.md'
  - 'Checklist': '22_checklist.md'
  - 'Templates': '23_templates.md'
  - 'Surveys': 'Surveys .md'
  - 'Architecture': 'architecture.md'
  - 'Scalability': 'scalabilty.md'
  
